version: '3.3'

services:
   db:
     image: mysql:8.0
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     env_file: .env
     environment:
       MYSQL_DATABASE: moovers_wordpress
     networks:
      - app-network

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "80:80"
     restart: always
     volumes:
       - wordpress:/var/www/wordpress/wordpress
     env_file: .env
     environment:
       - WORDPRESS_DB_HOST=db:3306
       - WORDPRESS_DB_USER=$MYSQL_USER
       - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
       - WORDPRESS_DB_NAME=moovers_wordpress
     networks:
      - app-network

   webserver:
    depends_on:
      - wordpress
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - wordpress:/var/www/wordpress/wordpress
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - app-network

volumes:
    db_data: {}
    wordpress:

networks:
  app-network:
    driver: bridge